### ISSUE TITLE
Future deployment of DDM on cmsweb

### ISSUE THREAD

**Issue by giffels** [dmwm/DDM#10]
Hi,

I have added the necessary user accounts and groups (_victor and _cmspopdb) to the system/deploy script. https://github.com/giffels/deployment/commit/cab5d369d8965892d5eaeabb3641a0ddd667c271

I have added forwarding rules for victor and cmspopdb to the appropriate frontend configurations. https://github.com/giffels/deployment/commit/d6c24dc53457e8147a1056d56d296d5b98ce0493

I have added a CMS Popularity box with links to victor and cmspopdb to the cmsweb welcome page. https://github.com/giffels/deployment/commit/c851e80b6a375681ea7d46ffb0e54c1cb729d029

A comparison of the feature branch to the dmwm:master can be found here https://github.com/giffels/deployment/compare/cmspopdb-configuration

**Things to do:**
  * Request a port range for victor and cmspopdb from the http group. Currently the forwarding rules are pointing to the dbs port. 

Cheers,
Manuel

**Comment by nikmagini** [comment]
Deployed to cmsweb in 1505 release, closing
