### ISSUE TITLE
Google data analytics

### ISSUE THREAD

**Issue by DomenicoGiordano** [dmwm/DDM#19]
Google data analytics is included to monitor the web accesses, both for CMS Popualrity and Victor. Evaluate if it's still needed or should be removed

**Comment by nikmagini** [comment]
Hi,

this was solved in the deployment to cmsweb removing ga.js at the level of spec files :

popdbweb:
https://github.com/cms-sw/cmsdist/blob/comp_gcc481/popdbweb.spec#L28

victorweb:
https://github.com/cms-sw/cmsdist/blob/comp_gcc481/victorweb.spec#L17
https://github.com/cms-sw/cmsdist/blob/comp_gcc481/victorweb.spec#L21

Closing
N.
