### ISSUE TITLE
CMSSW Popualrity: request a production DB instance

### ISSUE THREAD

**Issue by DomenicoGiordano** [dmwm/DDM#23]
A production DB instance should be asked to collect the CMSSW Popularity data.
Currently data are collected in int11r DB, but this DB has not backup.

Please evaluate also if a migration of the current data from int11r to the new production DB schema is needed and in case coordinate with DBA to perform data migration.
I would strongly suggest to move data in production DB.

When the production DB schema will be ready, redirect the collection workflow to this DB.

**Comment by nikmagini** [comment]
Update: CMSSW popularity data was migrated to INT9R (CMS Integration DB) on May 22nd, if all goes well we will request the migration to the CMSR production DB in the upcoming weeks.

**Comment by nikmagini** [comment]
Update: CMSR deployment requested

https://cern.service-now.com/service-portal/view-request.do?n=RQF0467028

**Comment by nikmagini** [comment]
Migration to CMSR completed during the weekend of Oct 30 2015:

https://cern.service-now.com/service-portal/view-request.do?n=RQF0514205
