### ISSUE TITLE
CMS Popularity web: development instance alias

### ISSUE THREAD

**Issue by DomenicoGiordano** [dmwm/DDM#24]
There is a alias usable to point to a development/integration instance of the CMS popularity system.
This alias is CMS-POP-DEV--LOAD-xxx-
cms-popularity-dev (the redirector url) points to this alias, to expose the dev/integration instance..
Currently CMS-POP-DEV points to a dashboard machine. 
When a development (integration) instance is ready in a cms vobox, please ask to remove the alias from the dashboard machine.

Note from Andreas P. to access the machine through web redirector:  
open port 443 (https) open, either for any machine, or for a subset (CERN hosts) or for a single machine (likely by IP address). If it’s by host, you’ll need to change 137.138.162.187 (vocms147, the old -dev front-end) to 128.142.243.211 (vocms0148, the new -dev front-end).

**Comment by nikmagini** [comment]
Hi,

obsolete since the migration of popularity to cmsweb - we now have a preprod instance on cmsweb-testbed.cern.ch and can deploy new dev instances at will on VMs.

Closing

Cheers
N
