### ISSUE TITLE
update link to support tickets

### ISSUE THREAD

**Issue by DomenicoGiordano** [dmwm/DDM#36]
The following web pages [*] include a link for the support requests from users.
The link points to the ticket system of https://svnweb.cern.ch/trac/popdb/ 
that is now obsolete and not maintained anymore. 
It should be replaced by new links to the gitHub project (or something else t.b.d.)

Domenico

[*]
1) submenu Support-> Wiki and BugReport for the urls
https://cms-popularity.cern.ch/popdb  
and 
https://cms-popularity.cern.ch/popdb/xrdpopularity/

2) submenu Bug&Requests at
https://cms-popularity.cern.ch/victor/accounting

**Comment by nikmagini** [comment]
Deployed in production in HG1509
