### ISSUE TITLE
Aggregate CRAB popularity data by SubmissionTool

### ISSUE THREAD

**Issue by nikmagini** [dmwm/DDM#97]
Since the beginning of Sep 2015, WMAgent started to report file access data to the Dashboard. This is picked up by the CRAB popularity collector, so the popularity metrics now include also production jobs submitted via WMAgent.
Need to make sure that the production jobs can be distinguished from analysis jobs in the DB MVs and in the plots - we should be able to use the SubmissionTool field in the raw file access records for this.

**Comment by ericvaandering** [comment]
There are some other differences just in the file access record if that helps. A lot of info missing in the WMAGent one.

**Comment by nikmagini** [comment]
Change deployed in production with popdbweb 0.5.0 on cmsweb on June 7th:
- added submissiontool field to base MV_DS_STAT0 mview
- created new aggregated mviews with/without wmagent stats
- added parameter includewmagent (default=n) to APIs
Closing
